### PR TITLE
Unwrap optionals with dynamic cast

### LINKED ISSUE #3183: Dynamic casting should unwrap optional values
### Why / Impact

Developer convenience

### Current Behavior

Dynamic casting (failable casting `as?`, and force casting `as!`) an optional value (potentially type-erased to an existential) to a non-optional type currently fails (e.g. failable casting results in `nil`).

### Expected Behavior

I expected (but perhaps shouldn't have) that an optional value being casted into a subtype it conforms to would unwrap it. I'm really not sure if this is a bug or if it's expected though

### Steps To Reproduce

I've made a repro contract/transactions to demonstrate

https://github.com/austinkline/cadence-burner-bug

### Environment

```markdown
- Cadence version:Version: v1.15.0-cadence-v1.0.0-preview.12, Commit: c582e63baf4581e4cf021a9b1917c198ca5b6065
- Network: emulator
```

### PR DESCRIPTION
**Pull request by RZhang05**
Closes #3183

## Description

Dynamic casting now unwraps optionals following the behaviour of Swift.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/interpreter/interpreter_expression.go [hunk 1]
```diff
@@ -1335,6 +1335,12 @@ func (interpreter *Interpreter) VisitCastingExpression(expression *ast.CastingEx
 		// thus this is the only place where it becomes necessary to "instantiate" the result of a map to its
 		// concrete outputs. In other places (e.g. interface conformance checks) we want to leave maps generic,
 		// so we don't substitute them.
+
+		// if the target is anystruct or anyresource we want to preserve optionals
+		if !(expectedType == sema.AnyStructType || expectedType == sema.AnyResourceType) {
```
Comment (SupunS) [inline runtime/interpreter/interpreter_expression.go:1340]: We might have to also unwrap `expectedType` type before performing this check.
For e.g: If the targetType is an optional of AnyStruct (`AnyStruct?`), then it will pass the check and will unbox the optional value, which it shouldn't. i.e:
```cadence
let x: Int??? = 42
let y: AnyStruct = x as! AnyStruct?
```

File: runtime/tests/interpreter/dynamic_casting_test.go [hunk 2]
```diff
@@ -3870,3 +3870,177 @@ func TestInterpretDynamicCastingReferenceCasting(t *testing.T) {
...
+			t,
+			inter,
+			interpreter.NewUnmeteredSomeValueNonCopying(
+				interpreter.NewUnmeteredSomeValueNonCopying(
+					interpreter.NewUnmeteredIntValueFromInt64(42),
+				),
+			),
+			inter.Globals.Get("y").GetValue(inter),
+		)
+	})
```
Comment (SupunS) [inline runtime/tests/interpreter/dynamic_casting_test.go:4045]: Tests are great! Thank you for covering all these different cases.
Can you please also add a test for resources, and `AnyResource` as well?

**Review by SupunS — COMMENTED** [review]
Looks good! Nice to see the fix is kept simple 👌

File: runtime/interpreter/interpreter_expression.go (hunk 1 above)
Comment (RZhang05) [reply runtime/interpreter/interpreter_expression.go]: Good point, added this unwrapping.

File: runtime/tests/interpreter/dynamic_casting_test.go (hunk 2 above)
Comment (RZhang05) [reply runtime/tests/interpreter/dynamic_casting_test.go:4045]: Added some tests for resources covering the expected use cases.

**Review by SupunS — APPROVED** [review]
LGTM!

File: runtime/tests/interpreter/dynamic_casting_test.go [hunk 3]
```diff
@@ -3870,3 +3870,365 @@ func TestInterpretDynamicCastingReferenceCasting(t *testing.T) {
...
+		require.NoError(t, err)
+		require.Equal(t, interpreter.NewUnmeteredStringValue("hello"), result)
+	})
+
+	t.Run("return nested optional as?", func(t *testing.T) {
+		t.Parallel()
+
+		code := `
+			let x: Int??? = 42
+			let y: Int?? = x as? Int?
```
Comment (turbolent) [inline runtime/tests/interpreter/dynamic_casting_test.go:4008]: Can you please also add a test case for this scenario (`Int???` casted to `Int?`) with the `as!` operator?

File: runtime/tests/interpreter/dynamic_casting_test.go [hunk 4]
```diff
@@ -3870,3 +3870,365 @@ func TestInterpretDynamicCastingReferenceCasting(t *testing.T) {
...
+			inter.Globals.Get("y").GetValue(inter),
+		)
+	})
+
+	t.Run("return nested optional as!", func(t *testing.T) {
+		t.Parallel()
+
+		code := `
+			let x: Int??? = 42
+			let y: Int?? = x as! Int??
```
Comment (turbolent) [inline runtime/tests/interpreter/dynamic_casting_test.go:4030]: Can you please also add a test case for this scenario (`Int???` casted to `Int??`) with the `as?` operator?

**Review by turbolent — APPROVED** [review]
Great work!

+1 on what @SupunS said, it's great that the implementation of this improvement is so simple.

Initially I was surprised this worked, I had assumed we would need to unbox only to the requested "level" of nesting. However, after looking at the rest of the implementation, this works because we box up the value again to the requested level again below (`value = interpreter.ConvertAndBox(locationRange, value, valueSemaType, expectedType`) 👍

**Comment by turbolent** [comment]
Related: Swift's dynamic casting is actually way more complicated then I thought https://github.com/swiftlang/swift/blob/main/docs/DynamicCasting.md 😅

File: runtime/tests/interpreter/dynamic_casting_test.go (hunk 3 above)
Comment (RZhang05) [reply runtime/tests/interpreter/dynamic_casting_test.go:4008]: Added.

File: runtime/tests/interpreter/dynamic_casting_test.go (hunk 4 above)
Comment (RZhang05) [reply runtime/tests/interpreter/dynamic_casting_test.go:4050]: Added.

**Review by turbolent — APPROVED** [review]
Great work!
