### PR TITLE
[4062-part-3] Update Cadence Errors

### LINKED ISSUE #4062: Improve Cadence Errors to Support LLM Efficiency
### Issue to be solved

Cadence errors, are not sufficiently informative for LLMs to solve linter errors on their own, particularly for pre-1.0 keywords.  IE:

```
pub fun foo() {}
```

Results in an error: `'pub' is no longer a valid access keyword`

This isn't sufficient information for an LLM to solve on it's own, and I don't think it includes a link to more information.

### Suggested Solution

Improve the error messages, link to the documentation, and ideally provide suggested fixes, so that tools like Cursor and other agent-based tools can automatically fix these errors. Agents are even able to read the referenced link and include that information in their solutions.

#### High priority

Primary focus is on on improving _existing_ errors, in particular their messages and secondary messages, and adding links to the documentation, as well as migration notes for errors related to pre-Cadence 1.0.

The documentation links and migration notes should be surfaced in the language server (https://github.com/onflow/cadence-tools/issues/484).

#### Lower priority

- Add suggested fixes for errors where possible
- Show migration note and documentation link in "pretty"/"console" output

### Out of scope

- Adding error codes
- Adding additional errors

### Errors for features that lack documentation

- [x] Member access / dot operator / optional chaining
- [x] Pragmas
- [x] Generics (e.g. type instantiations, function invocation type arguments, etc.) 
- [x] Complete list of usages and rules for all punctuation characters: (), {}, [], <>, `, ., |, (comma)
- [x] Whitespace rules
- [x] Improve documentation for casting/downcasting
- [ ] Explicit list/statement of where resources can be declared (https://cadence-lang.org/docs/language/resources)
- [x] Fixed point literal scale/range (sema.InvalidFixedPointLiteralRangeError, sema.InvalidFixedPointLiteralScaleError)
- [ ] Documentation of how contract-level fields work (https://cadence-lang.org/docs/language/contracts)
- [ ] Comparison rules, what can and cannot be compared (https://cadence-lang.org/docs/language/operators/comparison-operators)
- [x] Indexing

Some features / errors are internal / non-user facing and should not be documented because they are not part of the "official" language:

- `native`/`static` modifiers

### PR DESCRIPTION
**Pull request by briandoyle81**
Work towards #4062

NOTE: Part 2 was merged with part 1 and no longer exists independently.

## Description

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by turbolent — COMMENTED** [review]
The "content" of the added secondary errors and documentation links look good 👍 

It might be good to introduce dedicated error types, like in `sema`, to avoid duplicating the error message, secondary error message, and documentation link in multiple places; it clutters the parser logic and makes changes error prone (e.g. messages get out of sync).

I'll make the suggested changes and push them to this PR.

**Comment by turbolent** [comment]
@RZhang05 @SupunS this should be ready for review now

**Comment by turbolent** [comment]
Good catch @RZhang05! I've opened #4132 to prevent such mistakes in the future

File: parser/declaration.go [hunk 1]
```diff
@@ -1636,13 +1594,7 @@ func parseMemberOrNestedDeclaration(p *parser, docString string) (ast.Declaratio
...
 
 			case KeywordCase:
-				if purity != ast.FunctionPurityUnspecified {
-					return nil, NewSyntaxError(*purityPos, "invalid view modifier for enum case")
-				}
-				err := rejectStaticAndNativeModifiers(p, staticPos, nativePos, common.DeclarationKindEnumCase)
-				if err != nil {
-					return nil, err
-				}
+				rejectNonAccessModifiers(p, staticPos, nativePos, purityPos, common.DeclarationKindEnumCase)
```
Comment (SupunS) [inline parser/declaration.go:1597]: Is it intentional that now the parser would continue to parse, in case of an error?

**Review by SupunS — APPROVED** [review]
Nice!
