### PR TITLE
Fix integer conversion

### LINKED ISSUE #1126: Number Types Convert Incorrectly
This code:

```
  log(Int(UInt64(1)))
  log(Int(UInt64(18446744073709551615)))
```

logs:

```
18:20:43 Script 1
18:20:43 Script -1
```

https://play.onflow.org/f7457773-a35b-41f9-9296-cb0d73add49d?type=script&id=247df2fe-9acd-48bd-bba0-6f232801e478

That behaviour is unexpected. I have just encountered some code relying on it, and I have warned the developer that they should not do so.

@turbolent (thank you for looking at this!) says:

> I think this is a bug, caused by an internal conversion from uint64 to int, which silently overflows in Go

and that we should clean up code in the golang codebase marked:

> `// TODO: handle overflow`

I would like to attempt to fix this but I am slammed this week. If this can wait I can take it on, but if not someone else may need to.

### PR DESCRIPTION
**Pull request by turbolent**
Closes #1126 

## Description

- Fix conversion of integers > `math.MaxInt64`: 
  Implement `BigNumberValue` for `UInt64` and `Word64`
- Handle overflow/underflow when converting number values to `int` (in `ToInt()`)
- Add an extensive test case which performs number conversions between all integer types, for various values ("typical" value, overflowing, underflowing, and max value)

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/tests/interpreter/integers_test.go [hunk 1]
```diff
@@ -453,6 +455,224 @@ func TestInterpretIntegerLiteralTypeConversionInReturnOptional(t *testing.T) {
...
+		expectedValue interpreter.Value,
+		expectedError error,
+	) {
+
+		inter := parseCheckAndInterpret(t,
+			fmt.Sprintf(
+				`
+				  fun test(value: %[1]s): %[2]s {
+                      return %[2]s(value)
+                  }
```
Comment (SupunS) [inline runtime/tests/interpreter/integers_test.go:476]:
```suggestion
                  fun test(value: %[1]s): %[2]s {
                      return %[2]s(value)
                  }
```

**Review by SupunS — APPROVED** [review]
