### PR TITLE
Fix "log" crashing the REPL

### LINKED ISSUE #2106: Calling log crashes the REPL
### Problem

Calling `log` in the REPL currently throws a nil dereference error instead of the expected behaviour of printing to stdout. 

OS: macos 12.2.1 (2021 M1 MBP 14")
Version: Flow CLI v0.41.2
Logs:

```
Welcome to Cadence v0.28.0!
Type '.help' for assistance.

1> log("hi")
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1008a285c]

goroutine 1 [running]:
github.com/onflow/cadence/runtime.(*REPL).Accept.func1()
        github.com/onflow/cadence@v0.28.0/runtime/repl.go:148 +0xd4
panic({0x101a6e460, 0x10287b4e0})
        runtime/panic.go:884 +0x204
github.com/onflow/cadence/runtime/interpreter.(*Variable).GetValue(...)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/variable.go:29
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitIdentifierExpression(0x140000f8fc0, 0x1400059d7d0)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_expression.go:244 +0x4c
github.com/onflow/cadence/runtime/ast.AcceptExpression[...]({0x101cf15a0?, 0x1400059d7d0}, {0x101cfc5f8, 0x140000f8fc0})
        github.com/onflow/cadence@v0.28.0/runtime/ast/visitor.go:221 +0x1e8
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).evalExpression(...)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_expression.go:252
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitInvocationExpression(0x140000f8fc0, 0x14000594d20)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_expression.go:814 +0xf8
github.com/onflow/cadence/runtime/ast.AcceptExpression[...]({0x101cf16c0?, 0x14000594d20}, {0x101cfc5f8, 0x140000f8fc0})
        github.com/onflow/cadence@v0.28.0/runtime/ast/visitor.go:218 +0x21c
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).evalExpression(...)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_expression.go:252
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitExpressionStatement(0x140006a5970?, 0x100395180?)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_statement.go:564 +0x3c
github.com/onflow/cadence/runtime/ast.AcceptStatement[...]({0x101ced410?, 0x1400056afd0}, {0x101cf7d60, 0x140000f8fc0})
        github.com/onflow/cadence@v0.28.0/runtime/ast/visitor.go:135 +0x3bc
github.com/onflow/cadence/runtime.(*REPL).Accept(0x140004eb650, {0x14000053240, 0xa, 0x10})
        github.com/onflow/cadence@v0.28.0/runtime/repl.go:233 +0x558
github.com/onflow/cadence/runtime/cmd/execute.RunREPL.func3({0x14000053150?, 0x0?})
        github.com/onflow/cadence@v0.28.0/runtime/cmd/execute/repl.go:69 +0x110
github.com/c-bata/go-prompt.(*Prompt).Run(0x14000022fc0)
        github.com/c-bata/go-prompt@v0.2.5/prompt.go:84 +0x628
github.com/onflow/cadence/runtime/cmd/execute.RunREPL()
        github.com/onflow/cadence@v0.28.0/runtime/cmd/execute/repl.go:112 +0x288
github.com/onflow/flow-cli/internal/cadence.glob..func1(0x102898540?, {0x1028ed8c0?, 0x0?, 0x0?})
        github.com/onflow/flow-cli/internal/cadence/cadence.go:35 +0x3c
github.com/spf13/cobra.(*Command).execute(0x102898540, {0x140001b4010, 0x0, 0x0})
        github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x140002cec80)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        github.com/onflow/flow-cli/cmd/flow/main.go:84 +0x4a0
```

### Steps to Reproduce

1. open a terminal
2. type 'f'
3. type 'l'
4. type 'o'
5. type 'w'
6. type ' '
7. type 'c'
8. type 'a'
9. type 'd'
10. type 'e'
11. type 'n'
12. type 'c'
13. type 'e'
14. type Enter. now you're in the cadence REPL.
15. type 'l'
16. type 'o'
17. type 'g'
18. type '('
19. type '0'
20. type ')'
21. type Enter. 
22. cry

### PR DESCRIPTION
**Pull request by dreamsmasher**
Closes #2106 

## Description

Calling/referencing `log` in the REPL causes a crash now, because the `log` function seems to be bound in the checker's environment but not the interpreter. We would expect a "name not found" error if the function simply wasn't defined at all.

A quick git-bisect shows that this bug was introduced somewhere in commit 98d603797eea90ca73189d7ff36d79cb227c6b24 (#1825). I've manually added `log` back to the interpreter's `BaseActivation` for now, but some more investigation is necessary to see if any other standard library functions have been lost in the REPL. Some unit tests would be nice to prevent this from reoccurring.
______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/interpreter/interpreter.go [hunk 1]
```diff
@@ -292,15 +292,17 @@ var _ ast.DeclarationVisitor[StatementResult] = &Interpreter{}
 var _ ast.StatementVisitor[StatementResult] = &Interpreter{}
 var _ ast.ExpressionVisitor[Value] = &Interpreter{}
 
-// BaseActivation is the activation which contains all base declarations.
```
Comment (turbolent) [inline runtime/interpreter/interpreter.go:295]: This declaration should stay as-is, we shouldn't ever need to recreate the whole base activation

File: runtime/repl.go [hunk 2]
```diff
@@ -66,15 +67,18 @@ func NewREPL(
 
 	storage := interpreter.NewInMemoryStorage(nil)
 
-	// NOTE: storage option must be provided *before* the predeclared values option,
-	// as predeclared values may rely on storage
+	// necessary now due to log being looked up in the
+	// interpreter's activations instead of the checker
+	baseActivation := interpreter.NewBaseActivation()
```
Comment (turbolent) [inline runtime/repl.go:72]: Instead of recreating a whole new base activation, it's cheaper to just create a new activation and set the base activation as the parent:

```suggestion
	baseActivation := activations.NewActivation[*interpreter.Variable](nil, interpreter.BaseActivation)
```

File: runtime/repl.go [hunk 3]
```diff
@@ -66,15 +67,18 @@ func NewREPL(
...
+	interpreter.Declare(baseActivation, stdlib.NewLogFunction(cmd.StandardOutputLogger{}))
```
Comment (turbolent) [inline runtime/repl.go:73]: Maybe add a comment to the equivalent declaration of for the checker in `DefaultCheckerConfig`:
https://github.com/onflow/cadence/blob/e2b6a824df0cad26f60d493e9113acef70c2a909/runtime/cmd/cmd.go#L88

```
// NOTE: also ensure to implement all definitions, e.g. for the `REPL` in `NewREPL`
```

**Review by turbolent — COMMENTED** [review]
Nice, thanks for fixing this

File: runtime/interpreter/interpreter.go (hunk 1 above)
Comment (dreamsmasher) [reply runtime/interpreter/interpreter.go:295]: ah, was just a cautionary clone since I append a binding to `log` later on, guess it doesn't mutate the base activation.

**Review by turbolent — APPROVED** [review]

File: runtime/interpreter/interpreter.go (hunk 1 above)
Comment (turbolent) [reply runtime/interpreter/interpreter.go]: Yeah, the parent base activation isn't modified, the activation is basically a linked list.

**Review by dsainati1 — APPROVED** [review]
