### PR TITLE
Fix definite field initialization analysis 

### LINKED ISSUE #1405: Definite initialization is too conservative
### Problem

PR #1332 fixed definite initialization analysis, but also made it more conservative. 

### Steps to Reproduce

For example, the following test cases fail, but should not:

```go

func TestCheckFieldInitializationAfterJump(t *testing.T) {

	t.Parallel()

	t.Run("while, continue", func(t *testing.T) {

		t.Parallel()

		_, err := ParseAndCheck(t, `
            struct Test {
                var foo: Int

                init(foo: Int) {
                    while true {
                        continue
                    }
                    self.foo = foo
                }
            }
        `)

		require.NoError(t, err)
	})

	t.Run("while, break", func(t *testing.T) {

		t.Parallel()

		_, err := ParseAndCheck(t, `
            struct Test {
                var foo: Int

                init(foo: Int) {
                    while true {
                        break
                    }
                    self.foo = foo
                }
            }
        `)

		require.NoError(t, err)
	})

	t.Run("for, continue", func(t *testing.T) {

		t.Parallel()

		_, err := ParseAndCheck(t, `
            struct Test {
                var foo: Int

                init(foo: Int) {
                    for i in [] {
                        continue
                    }
                    self.foo = foo
                }
            }
        `)

		require.NoError(t, err)
	})

	t.Run("for, break", func(t *testing.T) {

		t.Parallel()

		_, err := ParseAndCheck(t, `
            struct Test {
                var foo: Int

                init(foo: Int) {
                    for i in [] {
                        break
                    }
                    self.foo = foo
                }
            }
        `)

		require.NoError(t, err)
	})

    t.Run("switch, break", func(t *testing.T) {

		t.Parallel()

		_, err := ParseAndCheckWithPanic(t, `
          struct Test {
              let n: Int

              init(n: Int) {
                  switch n {
                  case 1:
                      break
                  }
                  self.n = n
              }
          }
        `)

		require.NoError(t, err)
	})

}
```

### Suggested Solution

Return info tracking should probably differentiate between switch-case jumps (break) and loop breaks/continues

### PR DESCRIPTION
**Pull request by SupunS**
Closes #1405

## Description

`MaybeJumpedOrReturned` (now `MaybeReturned`) was used only to determine whether a branch of the function has a 'return'. Marking it as `true` for jumps (`break` and `continue` statements) was going against the above assumption/usage.

Reverted the change of using that flag for both jumps and returns, and continue to use it for returns only.
______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/sema/return_info.go [hunk 1]
```diff
@@ -19,18 +19,18 @@
 package sema
 
 type ReturnInfo struct {
-	// MaybeJumpedOrReturned indicates that the (branch of) the function
-	// contains a potentially taken return, break, or continue statement
-	MaybeJumpedOrReturned bool
-	DefinitelyReturned    bool
-	DefinitelyHalted      bool
-	DefinitelyJumped      bool
+	// MaybeReturned indicates that (a branch of) the function
```
Comment (turbolent) [inline runtime/sema/return_info.go:22]: Thank you for fixing the typo here (double "the"). Sorry to be so pernickety, but maybe use "the" branch in the parentheses, as this return info is not for some branch of the function, but "this particular one" / "the current one".
Just worries "a branch" could be misinterpreted to mean "some branch" / "another branch" in the function.

```suggestion
	// MaybeReturned indicates that (the branch of) the function
```

**Review by turbolent — APPROVED** [review]
Nice work! 👏 Glad it was an easy fix, I couldn't quite see it 🙂
