### PR TITLE
Fix resource loss analysis and definite initialization analysis

### LINKED ISSUE #1325: Resource object may lost when using switch-case to destroy
### Problem
Hi guys,
We are from the Increment Labs which focusing on the flow development and ecosystem. We know cadence takes resouce security testing seriously. However, we found that:
> If a switch-case without default is used to destroy the resource object, the compiler fails to make a judgement on whether the resource is passed correctly. When passing a param which is not captured by the switch-case, the resource disappears.

### Steps to Reproduce

Testcase on playground:
https://play.onflow.org/813992f4-5e98-4449-8421-9a753b607d5f?type=account&id=0
```js
    // deploy successfully
    pub fun test(n:Int, res:@R) {
        // switch with no default
        switch n {
            case 1:
                log("1")
                destroy res
            case 2:
                log("2")
                destroy res
        }
    }
```
```js
    let r <- HelloWorld.mintR()
    // if pass n = 3, switch failed in catching and resource disappears
    HelloWorld.test(n: 3, res: <-r)
```

### PR DESCRIPTION
**Pull request by turbolent**
Closes #1325 

Based heavily on #1329, thank you @SupunS 🙏 

Investigating the issue I also discovered that the definite initialization analysis suffered from the same problem.

## Description

- Fix and simplify resource tracking / resource loss detection (82c260aab267981de61551782775294a2af569d2):
  -  Consider jumps (break and continue statements) when merging then/else branches' invalidations into the parent
  - Don't record resource invalidations if the code adding the invalidation is unreachable
- Consider jumps in definite initialization analysis and improve dead code reporting (88b9fbe6f850a5eb0a483961cdf53fc472776088)
  - In addition to when maybe a return statement occured, initializations should also be ignored when maybe a jump (break or continue statement) occured
  - In addition to when a definite return statement occurs, code is also unreachable if a definite jump (beak or continue statement) occurred before
- Add tests for resource loss analysis and definite initialization analysis fixes

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/sema/return_info.go [hunk 1]
```diff
@@ -21,7 +21,9 @@ package sema
 type ReturnInfo struct {
 	MaybeReturned      bool
 	DefinitelyReturned bool
+	MaybeJumped        bool
```
Comment (SupunS) [inline runtime/sema/return_info.go:24]: Is it now possible to merge `xxxReturned` and `xxxJumped` to a single flag?
Are there any use-cases of each being used individually? 🤔

File: runtime/tests/checker/resources_test.go [hunk 2]
```diff
@@ -2698,10 +2733,11 @@ func TestCheckInvalidResourceLossThroughReturn(t *testing.T) {
       }
     `)
 
-	errs := ExpectCheckerErrors(t, err, 2)
+	errs := ExpectCheckerErrors(t, err, 3)
 
 	assert.IsType(t, &sema.ResourceLossError{}, errs[0])
 	assert.IsType(t, &sema.UnreachableStatementError{}, errs[1])
+	assert.IsType(t, &sema.ResourceLossError{}, errs[2])
```
[the remark this answers is not in the document]
Comment (turbolent) [reply runtime/tests/checker/resources_test.go:2740]: Yes, there is now an additional error reported, but "over reporting" isn't a problem: The first resource loss error is reported by the resource loss check by the return statement, and the second is returned by the resource loss check at the end of the function. Both are correct and I don't think it is worth the effort to reduce over reporting

File: runtime/sema/return_info.go (hunk 1 above)
Comment (turbolent) [reply runtime/sema/return_info.go:24]: Maybe, I'll have a look 👍

File: runtime/tests/checker/resources_test.go [hunk 3]
```diff
@@ -5049,3 +5086,384 @@ func TestCheckEmptyResourceCollectionMove(t *testing.T) {
...
+                    default:
+                        destroy r
+                }
+            }
+        `)
+
+		require.NoError(t, err)
+	})
+
+	t.Run("switch-case: break in one case", func(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (turbolent) [reply runtime/tests/checker/resources_test.go:5405]: Good catch!

```suggestion
	t.Run("switch-case: destroy missing in default case", func(t *testing.T) {
```

File: runtime/sema/return_info.go (hunk 1 above)
Comment (turbolent) [reply runtime/sema/return_info.go]: Merged `MaybeReturned` and `MaybeJumped` in 3021117. `DefinitelyReturned` is used in `Checker.checkFunctionExits` independently to determine if a function with a return type also has a return statement, so `DefinitelyReturned` and `DefinitelyJumped` cannot be merged

Comment (SupunS) [reply runtime/sema/return_info.go]: I see. Thank you for checking!

**Review by SupunS — APPROVED** [review]
Nice! LGTM! 👌
