### PR TITLE
Fix value transfer type check

### LINKED ISSUE #1479: Cannot cast &FungibleToken.Vault to &FungibleToken.Vault{FungibleToken.Balance}
### Problem

When trying to cast a `&FungibleToken.Vault` type to a `&FungibleToken.Vault{FungibleToken.Balance}` type, you get this weird error: "Error invalid transfer of value: expected &FungibleToken.Vault{FungibleToken.Balance}". 

The same is true for other restricted types, like `&FungibleToken.Vault{FungibleToken.Receiver}` and `&FungibleToken.Vault{FungibleToken.Provider}`. I believe this is also a bug for &NonFungibleToken.Collection as well.

I have reproduced this error in both the playground and on the current version of TestNet. 

image

### Steps to Reproduce

https://play.onflow.org/0d50d978-20eb-4328-b75c-4aff5d42240f?type=account&id=f7be17c7-953e-4728-ac7b-e23337d5e215&storage=none

If you run the transaction in the playground above, you should see the error at hand.

### PR DESCRIPTION
**Pull request by turbolent**
Closes #1479 

## Description

When checking `T <: U{Vs}`, we currently require `T == U`, assuming both are composite values. 
However, the latter may actually be a type requirement.

Extend the subtyping check and require `T <: U`.

______

- [ ] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by turbolent** [comment]
Added another test case which shows that this is not just a problem for references, but an issue with composite dynamic type and restricted static type.

**Comment by turbolent** [comment]
Added yet another check which shows that this is actually a limitation of the type checker. The dynamic subtype check in the interpreter relies on this check to succeed

File: runtime/tests/interpreter/transfer_test.go [hunk 1]
```diff
@@ -34,52 +34,139 @@ func TestInterpretTransferCheck(t *testing.T) {
...
+		)
+		require.NoError(t, err)
+
+		_, err = inter.Invoke("test")
+		require.Error(t, err)
+
+		require.ErrorAs(t, err, &interpreter.ValueTransferTypeError{})
+	})
+
+	t.Run("contract and restricted type", func(t *testing.T) {
```
Comment (turbolent) [inline runtime/tests/interpreter/transfer_test.go:91]: These tests passed the type checking (correctly) and only failed at run-time due to the defensive value transfer check, which in addition to the static check, also checks subtyping for the underlying value.

**Review by dsainati1 — APPROVED** [review]

**Review by SupunS — APPROVED** [review]
