### PR TITLE
Fix and test sema to static type conversion

### LINKED ISSUE #2464: AuthAccount type equivalence check does not work
### Current Behavior

Type equivalence is not working as I would expect when I evaluate an AuthAccount capability I have borrowed.

If I evaluate them based on their actual types, they fail:
```
#allowAccountLinking

pub fun main(address: Address):AnyStruct {
  let acct = getAuthAccount(address)
  let p = /private/tmp

  acct.linkAccount(p)
  let capType = acct.getCapability<&AuthAccount>(p).borrow()!.getType()

  // Both of these return no
  // return Type<&AuthAccount>() == capType ? "yes" : "no" // returns no!
  return Type<AuthAccount>() == capType ? "yes" : "no" // returns no!
}
```

But if I evaluate based on their type identifiers:
```cadence
#allowAccountLinking

pub fun main(address: Address):Bool {
  let acct = getAuthAccount(address)
  let p = /private/tmp

  acct.linkAccount(p)
  let capType = acct.getCapability<&AuthAccount>(p).borrow()!.getType()

  return Type<AuthAccount>().identifier == capType.identifier // returns yes!
}
```

I dug a little deeper into it, and even their json is the same when printed from the flow runner. If you run [this script](https://run.ecdao.org?code=I2FsbG93QWNjb3VudExpbmtpbmcKCnB1YiBmdW4gbWFpbihhZGRyZXNzOiBBZGRyZXNzKTpbVHlwZV0gewogIGxldCBhY2N0ID0gZ2V0QXV0aEFjY291bnQoYWRkcmVzcykKICBsZXQgcCA9IC9wcml2YXRlL3RtcAoKICBhY2N0LmxpbmtBY2NvdW50KHApCiAgbGV0IGNhcFR5cGUgPSBhY2N0LmdldENhcGFiaWxpdHk8JkF1dGhBY2NvdW50PihwKS5ib3Jyb3coKSEuZ2V0VHlwZSgpCgogIHJldHVybiBbVHlwZTxBdXRoQWNjb3VudD4oKSwgY2FwVHlwZV0KfQo%3D&network=testnet&args=eyJhZGRyZXNzIjoiMHg0MDM4N2NlYTYyMjQyNWEzIn0%3D), you will get both types back and can compare them

### Expected Behavior

I would expect that a borrowed AuthAccount capability's type should either match `Type<AuthAccount>()` or `Type<&AuthAccount>()`, but it seems like neither do which is strange

### Steps To Reproduce

Run the following script:
```
#allowAccountLinking

pub fun main(address: Address):AnyStruct {
  let acct = getAuthAccount(address)
  let p = /private/tmp

  acct.linkAccount(p)
  let capType = acct.getCapability<&AuthAccount>(p).borrow()!.getType()

  return Type<AuthAccount>() == capType ? "yes" : "no" // returns no!
}
```

### Environment

```markdown
- Cadence version: v0.49.0
- Network: Emulator, Testnet
```

### PR DESCRIPTION
**Pull request by turbolent**
Closes #2464

## Description

The bug was caused by an inconsistent conversion between sema and static types:
while `interpreter.PrimitiveStaticTypeAuthAccount` was converted to `sema.AuthAccountType`,
`sema.AuthAccountType` was converted to `interpreter.CompositeStaticType`.

- Fix the `sema.Type` to `interpreter.StaticType` conversion for primitive static types.
- Add tests for sema to static type conversion, and static to sema type conversion.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by dsainati1** [comment]
If we really are converting types back and forth between `sema` and `static` forms multiple times, would it make sense to add a cache to these functions?

**Review by dsainati1 — APPROVED** [review]

File: runtime/interpreter/statictype_test.go [hunk 1]
```diff
@@ -972,3 +973,487 @@ func TestPrimitiveStaticTypeCount(t *testing.T) {
...
+		{
+			name:       "StoragePath",
+			semaType:   sema.StoragePathType,
+			staticType: PrimitiveStaticTypeStoragePath,
+		},
+		{
+			name:       "CapabilityPath",
+			semaType:   sema.CapabilityPathType,
+			staticType: PrimitiveStaticTypeCapabilityPath,
+		},
```
Comment (SupunS) [inline runtime/interpreter/statictype_test.go:1243]: This one is redundant. "Unparameterized Capability" test below is same as this one

**Review by SupunS — APPROVED** [review]

File: runtime/interpreter/statictype_test.go (hunk 1 above)
Comment (turbolent) [reply runtime/interpreter/statictype_test.go:1243]: This test is for the `CapabilityPath` type, not the `Capability` type.

Comment (SupunS) [reply runtime/interpreter/statictype_test.go:1243]: ah right! my bad! My eyes have been delusional
