### PR TITLE
Fix data race in sema/type_test.go

### LINKED ISSUE #2623: Data race in sema/type_test.go
Ran into this data race in in sema/type_test.go:

https://github.com/onflow/cadence/actions/runs/5424849656/jobs/9864802365?pr=2621

### PR DESCRIPTION
**Pull request by fxamacker**
Closes #2623

This PR fixes the data race in sema/type_test.go.

https://github.com/onflow/cadence/actions/runs/5424849656/jobs/9864802365?pr=2621

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/sema/type_test.go [hunk 1]
```diff
@@ -690,7 +690,7 @@ func TestIdentifierCacheUpdate(t *testing.T) {
 					cachedID := semaType.ID()
 
 					// clear cached identifiers for one level
-					semaType.cachedIdentifiers = nil
```
Comment (turbolent) [inline runtime/sema/type_test.go:693]: It looks like the test not only resets the cached identifier of the types defined in the program, but  of all types, including the built-in ones (which might be used concurrently somewhere else).

We should maybe improve the test and not reset the cached identifiers of the built-in types (`Location == nil`)

**Review by turbolent — COMMENTED** [review]
Thank you for identifying this issue and fixing it!

File: runtime/sema/type_test.go (hunk 1 above)
Comment (turbolent) [reply runtime/sema/type_test.go:693]: Improved this in [ad58840](https://github.com/onflow/cadence/pull/2624/commits/ad588404e7480000f8452be2ac2989919c6e69c9)

**Review by turbolent — APPROVED** [review]
Thanks!
