### PR TITLE
Fix Value.Type() returning Type referencing nil ptr for eight external values

### LINKED ISSUE #2387: Value.Type() can return a reference to a nil pointer
### Issue to be solved

Current implementations of `Value.Type()` can return a Type referencing a nil pointer.

This can make callers deference the nil pointer.

### Suggested Solution

Implementations of `Value.Type()` should return `nil` instead of a reference to a nil pointer.

### PR DESCRIPTION
**Pull request by fxamacker**
Changes include:
- Changed type of `Dictionary.DictionaryType` from `Type` to `*DictionaryType`.
- Changed `Type()` to check and return nil `Type`, instead of `Type` referencing nil pointer for these external values:
  - `Dictionary`
  - `Struct`
  - `Resource`
  - `Attachment`
  - `Event`
  - `Contract`
  - `Enum`
  - `Function`

Closes #2387

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: values.go [hunk 1]
```diff
@@ -1453,6 +1453,11 @@ func NewMeteredDictionary(
 func (Dictionary) isValue() {}
 
 func (v Dictionary) Type() Type {
+	if v.DictionaryType == nil {
```
Comment (turbolent) [inline values.go:1456]: Took me a moment to realize why this is needed: Go creates a typed nil without it. (Typed nil strikes again!) Too bad this is necessary, but seems right, given that allows us to keep the `Type() Type` function.

**Review by turbolent — COMMENTED** [review]
Thanks for fixing this!

Unfortunately, introducing typed nils is too easy. 

We should maybe add tests that avoid regressions for these functions, and in addition, prevent incorrect implementations in the future (e.g. by creating an empty instance of each `Type` implementation, and then, as each nested type is automatically `nil`, the a call to `Type()` should be equal to the untyped nil (`== nil`).

Let me try adding that.

File: values_test.go [hunk 2]
```diff
@@ -635,6 +635,8 @@ func TestGetType(t *testing.T) {
 			reflect.TypeOf(Event{}):      {},
 			reflect.TypeOf(Resource{}):   {},
 			reflect.TypeOf(Struct{}):     {},
+			reflect.TypeOf(Enum{}):       {},
+			reflect.TypeOf(Attachment{}): {},
```
Comment (turbolent) [inline values_test.go:639]: So while extending these tests I noticed that the existing code relying on the `reflect.typelinks` function doesn't include these two types for whatever reason. I saw the code was taken from https://stackoverflow.com/questions/32132064/how-to-discover-all-package-types-at-runtime.

What is so special about `Enum` that it isn't included, but e.g. `Struct` is? 🤔

Comment (SupunS) [reply values_test.go:639]: Maybe because this file doesn't instantiate any `Enum` instances? (should have been a test case there for enums!)

Comment (SupunS) [reply values_test.go:639]: oh well, that looks like a problem with this test. It only can find types that are actually used inside this file 🥴

Comment (turbolent) [reply values_test.go:639]: So I tried to look a bit more into it and finally found and confirmed the problem:

`typenames` says:

```
// Only types we might want to look up are included:
// pointers, channels, maps, slices, and arrays.
```

If I add a simple statement like this, which converts to `any`, i.e. creates a pointer, `Enum` gets included:

```golang
fmt.Printf("%v\n", Enum{})
```

I can't find any alternative, so for now I'll remove the code relying on internals, and just manually list the `Value` implementations. This won't let us automatically handle new cases, but the current code may not even handle existing cases.

File: runtime/format/capability.go [hunk 3]
```diff
@@ -35,10 +35,3 @@ func StorageCapability(borrowType string, address string, path string) string {
 		path,
 	)
 }
-
-func AccountCapability(address string) string {
```
Comment (turbolent) [inline runtime/format/capability.go:39]: Dead code

**Comment by turbolent** [comment]
Refactored the existing tests and unified them with similar tests for `String()`, as well as added further missing test cases (e.g. `Function` and `Character`) in fcb25195cb486033ea78794f3e0fc7354b25cee3

**Review by SupunS — APPROVED** [review]

File: values.go [hunk 4]
```diff
@@ -2102,6 +2102,11 @@ func (v Function) Type() Type {
 	return v.FunctionType
 }
 
+func (v Function) WithType(functionType *FunctionType) Function {
+	v.FunctionType = functionType
+	return v
+}
+
```
Comment (fxamacker) [inline values.go:2109]: @turbolent  Thanks for adding new tests and refactoring existing tests!  Great work!  :+1: 

Only item I spotted is that I think adding `Function.WithType()` isn't necessary because `Function` is created with `FunctionType`.

```
func NewFunction(functionType *FunctionType) Function {
	return Function{
		FunctionType: functionType,
	}
}
```

Also, test data for `Function` may need to be adjusted for the same reason.

Comment (turbolent) [reply values.go]: Good point, reverted adding it in f45e8d26d073e07b3238c961493126b518e1cd9a

**Review by turbolent — APPROVED** [review]

**Review by SupunS — APPROVED** [review]
