### PR TITLE
Fix field initialization: nested intersection should not override outer set

### LINKED ISSUE #1523: initialization of field '...' in type 'Transaction'. not initialized
### Problem

Getting `initialization of field '...' in type 'Transaction'. not initialized` error in a case where an if-statement is used before the initialization.

I have created playground with simple example for this.

### Steps to Reproduce

1. Open https://play.onflow.org/5d70bfbb-5924-42c6-be20-fb73114db7af?type=tx&id=bd249ec1-3f55-4455-bcdb-beebed73765e&storage=none
2. Inspect the error message
3. Remove line 13
4. Inspect the effect

### PR DESCRIPTION
**Pull request by turbolent**
Closes #1523 

## Description

If-statement branches are checked using [`Checker.checkConditionalBranches`](https://github.com/onflow/cadence/blob/86f8b58fd259ea0f80b3fa3e74a92587d6a0cd3f/runtime/sema/check_conditional.go#L145-L145).
It temporarily creates a new child member set, checks each branch with the temporary member set (using [`Checker.checkWithInitializedMembers`](https://github.com/onflow/cadence/blob/86f8b58fd259ea0f80b3fa3e74a92587d6a0cd3f/runtime/sema/checker.go#L1646-L1661), then "merges" the result by building an intersection (a field is considered initialized if it was initialized in both branches).

The existing implementation was overwriting the outer if-statements member set.

Instead, mutate the current member set in-place when computing the intersection.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/tests/checker/initialization_test.go [hunk 1]
```diff
@@ -1,7 +1,7 @@
 /*
  * Cadence - The resource-oriented smart contract programming language
  *
- * Copyright 2019-2020 Dapper Labs, Inc.
+ * Copyright 2019-2022 Dapper Labs, Inc.
```
Comment (robert-e-davidson3) [inline runtime/tests/checker/initialization_test.go:4]: Aside: is there a tool that updates copyrights or did you do this manually?

**Review by robert-e-davidson3 — APPROVED** [review]

**Review by SupunS — APPROVED** [review]

File: runtime/tests/checker/initialization_test.go (hunk 1 above)
Comment (turbolent) [reply runtime/tests/checker/initialization_test.go:4]: I just saw it was outdated. I opened #1529 to make all copyright notices consistent
