### PR TITLE
Test type order insignificance

### LINKED ISSUE #2681: Dictionaries key'd by type are order-dependent
### Current Behavior

If I have a dictionary key'd by `Type`, the order of their interface conformance matters:

```cadence
import FungibleToken from 0x1

pub fun main(): String {
  let t1 = Type<&{FungibleToken.Provider, FungibleToken.Balance}>()
  let t2 = Type<&{FungibleToken.Balance, FungibleToken.Provider}>()

  let dict: {Type: Bool} = {}
  dict[t1] = true

  assert(dict[t2] != nil, message: "key not found!")
  return "Done"
}
```

However, if I compare the two types, they are equal:

```cadence
import FungibleToken from 0x1

pub fun main(): String {
  let t1 = Type<&{FungibleToken.Provider, FungibleToken.Balance}>()
  let t2 = Type<&{FungibleToken.Balance, FungibleToken.Provider}>()

  assert(t1 == t2, message: "types are not equal")

  return "Done"
}
```

### Expected Behavior

I expect that two types which are equal should match to the same key in a dictionary

If I have a type `&{A, B}` and it is equivalent to `&{B, A}`, then my expectation is that a dictionary key'd on types should match regardless of their order

### Steps To Reproduce

Run this script on the flow emulator:

```cadence
import FungibleToken from 0xee82856bf20e2aa6

pub fun main(): String {
  let t1 = Type<&{FungibleToken.Provider, FungibleToken.Balance}>()
  let t2 = Type<&{FungibleToken.Balance, FungibleToken.Provider}>()

  // this will pass
  assert(t1 == t2, message: "types are not equal")

  let dict: {Type: Bool} = {}
  dict[t1] = true

  // this will fail
  assert(dict[t2] != nil, message: "key not found!")

  return "done"
}
```

### Environment

```markdown
- Cadence version: v1.3.2 (flow cli version)
- Network: Emulator
```

### PR DESCRIPTION
**Pull request by turbolent**
Work towards #2681

## Description

Test that the order of types is insignificant, even across multiple transactions (encoding/decoding), for intersection types and authorizations (entitlements). In both cases the types are sets.

This was previously fixed in #2750 and #2749.

______

- [ ] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/storage_test.go [hunk 1]
```diff
@@ -5541,3 +5541,180 @@ func TestRuntimeAccountIterationMutation(t *testing.T) {
...
+          }
+        `)
+
+		tx2 := []byte(`
+          import Test from 0x1
+
+          transaction {
+              prepare(account: auth(Storage) &Account) {
+
+                  let t1 = Type<&{Test.A, Test.B}>()
```
Comment (turbolent) [inline runtime/storage_test.go:5620]: - Add a migration that migrates dictionary keys that are `Type` values, if the static type contains a restricted type (force re-hash and removal of old key / insert of new key) 
- Maybe we can force Go code to not use `==` through the Go code of embedding an incomparable, but zero size field 
    ```go
    type S struct {
        _ [0]func()
        /* ... */
    }
    ```

**Comment by turbolent** [comment]
@SupunS Could you please have a look here?

**Review by SupunS — APPROVED** [review]
Sorry, I thought I already reviewed/approved this.

LGTM!
