### PR TITLE
Review of Sema and Parser Errors

### LINKED ISSUE #4062: Improve Cadence Errors to Support LLM Efficiency
### Issue to be solved

Cadence errors, are not sufficiently informative for LLMs to solve linter errors on their own, particularly for pre-1.0 keywords.  IE:

```
pub fun foo() {}
```

Results in an error: `'pub' is no longer a valid access keyword`

This isn't sufficient information for an LLM to solve on it's own, and I don't think it includes a link to more information.

### Suggested Solution

Improve the error messages, link to the documentation, and ideally provide suggested fixes, so that tools like Cursor and other agent-based tools can automatically fix these errors. Agents are even able to read the referenced link and include that information in their solutions.

#### High priority

Primary focus is on on improving _existing_ errors, in particular their messages and secondary messages, and adding links to the documentation, as well as migration notes for errors related to pre-Cadence 1.0.

The documentation links and migration notes should be surfaced in the language server (https://github.com/onflow/cadence-tools/issues/484).

#### Lower priority

- Add suggested fixes for errors where possible
- Show migration note and documentation link in "pretty"/"console" output

### Out of scope

- Adding error codes
- Adding additional errors

### Errors for features that lack documentation

- [x] Member access / dot operator / optional chaining
- [x] Pragmas
- [x] Generics (e.g. type instantiations, function invocation type arguments, etc.) 
- [x] Complete list of usages and rules for all punctuation characters: (), {}, [], <>, `, ., |, (comma)
- [x] Whitespace rules
- [x] Improve documentation for casting/downcasting
- [ ] Explicit list/statement of where resources can be declared (https://cadence-lang.org/docs/language/resources)
- [x] Fixed point literal scale/range (sema.InvalidFixedPointLiteralRangeError, sema.InvalidFixedPointLiteralScaleError)
- [ ] Documentation of how contract-level fields work (https://cadence-lang.org/docs/language/contracts)
- [ ] Comparison rules, what can and cannot be compared (https://cadence-lang.org/docs/language/operators/comparison-operators)
- [x] Indexing

Some features / errors are internal / non-user facing and should not be documented because they are not part of the "official" language:

- `native`/`static` modifiers

### PR DESCRIPTION
**Pull request by briandoyle81**
Closes #4062 

## Description

A few clarifications and correcting a pre- and post-condition error that was linking to control flow documentation.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: sema/errors.go [hunk 1]
```diff
@@ -3358,7 +3358,7 @@ func (*InvalidMoveOperationError) Error() string {
 
 func (*InvalidMoveOperationError) SecondaryError() string {
 	return "the move operator (`<-`) can only be used on resources; " +
-		"remove the `<-` operator for the non-resource"
+		"use the assignment operator (`=`) for the non-resource"
```
Comment (turbolent) [inline sema/errors.go:3361]: This error is reported for the unary move, e.g. in `f(<-s)`, where `s` is a struct and not a resource. The operator should be removed.

```suggestion
		"remove the `<-` operator for the non-resource"
```

**Comment by briandoyle81** [comment]
@turbolent @SupunS thanks for the fast reviews!

Is this failing check something I need to resolve?  It looks like I do not, but wanted to double-check!

**Comment by turbolent** [comment]
@briandoyle81 No, this is an unrelated failure, the Emulator still needs to be updated to the latest Cadence version, you can ignore it
