### PR TITLE
Handle wrapped errors during storage iteration

### LINKED ISSUE #2200: Skip broken values during storage iteration
### Issue To Be Solved

As described in https://github.com/onflow/cadence/issues/2170, some storage values could be broken/fail to load, due to outdated contracts. This becomes problematic in cases like storage iteration etc.

### Suggested Solution

Improve the storage iteration API to skip broken values

### PR DESCRIPTION
**Pull request by SupunS**
Closes #2200

## Description

Unwrap the returned error and check for the error kind.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/interpreter/interpreter.go [hunk 1]
```diff
@@ -3479,11 +3480,17 @@ func (interpreter *Interpreter) newStorageIterationFunction(
 func (interpreter *Interpreter) checkTypeLoading(staticType StaticType) (typeError error) {
 	defer func() {
 		if r := recover(); r != nil {
-			switch r := r.(type) {
-			case errors.UserError, errors.ExternalError:
-				typeError = r.(error)
-			default:
-				panic(r)
+			rootError := r
+			for {
```
Comment (turbolent) [inline runtime/interpreter/interpreter.go:3484]: Maybe the unwrapping also has to be done in `userPanicToError`?

**Comment by SupunS** [comment]
Also added a FVM test: https://github.com/onflow/flow-go/commit/9e4b9a62f2901e81390f1c87b1a71b298b3961b8, to verify the behavior after the integration. Will open a PR to flow-go once a cadence version is released with this fix.
