### PR TITLE
Replace interface GetProgram and SetProgram with GetAndSetProgram

### LINKED ISSUE #2247: Runtime interface GetProgram and SetProgram calls must be in pairs
### Current Behavior

After calls to `runtime.Interface.GetProgram` calls to `SetProgram` are missing when an error is encountered. 

### Expected Behavior

`runtime.Interface` calls to `GetProgram` and `SetProgram` must be done in pairs, even if an error is encountered. 

### Steps To Reproduce

https://www.notion.so/dapperlabs/Storage-Iteration-with-broken-contracts-bug-91d98f9c23604ee7b585fba54a6d18a9

### Environment

```markdown
- Cadence version: v0.31.2
- Network: Testnet
```

### PR DESCRIPTION
**Pull request by turbolent**
⚠️ Depends on #2249
Closes #2247
Closes #2180 (replacement)

## Description

Bases on the great start by @janezpodhostnik  in #2180 🙏 

With #2249, all `GetProgram` and `SetProgram` calls are now balanced.
Finally, replace both functions with a single function `GetAndSetProgram`.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/contract_update_test.go [hunk 1]
```diff
@@ -75,24 +81,33 @@ func TestContractUpdateWithDependencies(t *testing.T) {
...
+		) {
 			_, isTransactionLocation := location.(common.TransactionLocation)
-			if checkGetSetProgram && !isTransactionLocation {
+			if checkGetAndSetProgram && !isTransactionLocation {
 				require.Equal(t, location, fooLocation)
 				require.False(t, getProgramCalled)
-				getProgramCalled = true
 			}
-			// Always force to get the old program from the source during the update.
-			return nil, nil
```
Comment (turbolent) [inline runtime/contract_update_test.go:86]: This was an incorrect implementation of `GetProgram`. Instead, it should return what it loaded. Also, programs are only effective during the duration of execution (e.g. of a transaction or script), not across them, so clear all programs. This is because contract updates are delayed, and the test runtime interface does not properly commit/overwrite the new programs

File: runtime/deployment_test.go [hunk 2]
```diff
@@ -283,7 +283,7 @@ func TestRuntimeTransactionWithContractDeployment(t *testing.T) {
 					"  |\n"+
 					"4 |               fun testCase() {}\n"+
 					"  |               ^\n",
-				1,
+				2,
```
Comment (turbolent) [inline runtime/deployment_test.go:286]: `codesAndPrograms` has now more information, which is better

File: runtime/environment.go [hunk 3]
```diff
@@ -355,103 +355,42 @@ func (e *interpreterEnvironment) ParseAndCheckProgram(
 func (e *interpreterEnvironment) parseAndCheckProgram(
```
Comment (turbolent) [inline runtime/environment.go:355]: `parseAndCheckProgram` no longer has the responsibility of calling `SetProgram` if `storeProgram` is true

File: runtime/storage_test.go [hunk 4]
```diff
@@ -3403,34 +3403,13 @@ func TestRuntimeStorageIteration(t *testing.T) {
...
-
-			runtimeInterface := &testRuntimeInterface{
+		newRuntimeInterface := func() Interface {
+			return &testRuntimeInterface{
 				storage: ledger,
 				getSigningAccounts: func() ([]Address, error) {
 					return []Address{address}, nil
 				},
 				resolveLocation: singleIdentifierLocationResolver(t),
-				getProgram: func(location Location) (*interpreter.Program, error) {
```
Comment (turbolent) [inline runtime/storage_test.go:3417]: The `getProgram` and `setProgram` really only checked the balancing of the `GetProgram` and `SetProgram` calls. Given that this is no longer possible, remove those assertions

File: runtime/environment.go [hunk 5]
```diff
@@ -577,48 +516,51 @@ func (e *interpreterEnvironment) getProgram(
...
 
-	e.codesAndPrograms.setProgram(location, program.Program)
+		return &interpreter.Program{
+			Program:     parsedProgram,
+			Elaboration: elaboration,
+		}, nil
+	}
 
-	return program, nil
+	if getAndSetProgram {
```
Comment (SupunS) [inline runtime/environment.go:545]: Can invert the condition to reduce the nesting here
e.g:
```go
if !getAndSetProgram {
    return load()
}

wrapPanic(func() {
...
}

**Review by SupunS — APPROVED** [review]

File: runtime/interface.go [hunk 6]
```diff
@@ -34,36 +34,25 @@ type Interface interface {
...
-	//   As SetProgram is called when GetProgram is nil, then SetProgram MUST also be called when
-	//   GetProgram returns a program. This prevents nondeterministic behaviour
-	//
-	// Deprecated: This function should be refactored to ensure that SetProgram is always called
-	//
-	GetProgram(Location) (*interpreter.Program, error)
-	// SetProgram sets the program for the given location.
-	SetProgram(Location, *interpreter.Program) error
+	// - This function MUST also return what was previously loaded,
+	//   it may NOT return something different or nothing/nil (!) after load was called.
```
Comment (janezpodhostnik) [inline runtime/interface.go:50]: what about the case where load itself returns:
- nil
- or an error

**Review by janezpodhostnik — APPROVED** [review]

File: runtime/interface.go (hunk 6 above)
Comment (turbolent) [reply runtime/interface.go]: Tried to improve the comment further in [e3cfb8e](https://github.com/onflow/cadence/pull/2254/commits/e3cfb8eee8c43a54d5ae2c8eb400e650324fe9a9)
