### PR TITLE
Fix parsing 'from' keyword in imported-identifiers

### LINKED ISSUE #534: Cannot use 'from' as an identifier in multiple imports
### Steps to Reproduce

 Cannot use  'from' as a follow-up identifier in the import statement. Can use as the first identifier though.

```go
import from from 0x01cf0e2f2f715450    // works

import from, hello from 0x01cf0e2f2f715450    //  works

import hello, from from 0x01cf0e2f2f715450  // syntax error: `expected identifier, got keyword "from" `
```

### PR DESCRIPTION
**Pull request by SupunS**
Closes #534

## Description

With this change, if the  `from` keyword is found while parsing the identifiers in an import declaration, it will look-ahead to see whether this `from` token is part of the imported-identifiers list, or is it the `from` keyword that precede the location.

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/parser2/declaration.go [hunk 1]
```diff
@@ -441,30 +441,38 @@ func parseImportDeclaration(p *parser) *ast.ImportDeclaration {
 
 			case lexer.TokenIdentifier:
 
-				if p.current.Value == keywordFrom {
+				if p.current.Value != keywordFrom {
```
Comment (SupunS) [inline runtime/parser2/declaration.go:444]: Refactored this snippet to reduce the nested levels

File: runtime/parser2/declaration.go [hunk 2]
```diff
@@ -562,6 +570,31 @@ func parseImportDeclaration(p *parser) *ast.ImportDeclaration {
...
+func isCurrentTokenAnImportedIdentifier(p *parser) bool {
+	p.startBuffering()
+
+	// skip the 'from' keyword.
+	p.next()
+	p.skipSpaceAndComments(true)
+
+	defer func() {
+		p.replayBuffered()
+	}()
```
Comment (turbolent) [inline runtime/parser2/declaration.go:584]: Should be possible to simplify this to

```suggestion
	defer p.replayBuffered()
```

Comment (turbolent) [reply runtime/parser2/declaration.go:584]: Also, maybe move this to the top, right after `p.startBuffering()`, so the start and stop are grouped

File: runtime/parser2/declaration.go [hunk 3]
```diff
@@ -441,30 +441,38 @@ func parseImportDeclaration(p *parser) *ast.ImportDeclaration {
...
+						"expected %s, got keyword %q",
+						lexer.TokenIdentifier,
+						p.current.Value,
+					))
 				}
 
+				identifier := tokenToIdentifier(p.current)
+				identifiers = append(identifiers, identifier)
+
+				expectCommaOrFrom = true
```
Comment (turbolent) [inline runtime/parser2/declaration.go:474]: Looks like this code is now duplicated from above (the code in the `if p.current.Value != keywordFrom {` branch)

File: runtime/parser2/declaration.go [hunk 4]
```diff
@@ -562,6 +570,31 @@ func parseImportDeclaration(p *parser) *ast.ImportDeclaration {
 	}
 }
 
+// isCurrentTokenAnImportedIdentifier check whether the current token
+// needs to be processed as an imported identifier or not.
+func isCurrentTokenAnImportedIdentifier(p *parser) bool {
```
Comment (turbolent) [inline runtime/parser2/declaration.go:575]: Given that this function is considering the next token (it skips the current), maybe rename this function

**Review by turbolent — COMMENTED** [review]
Nice!

**Review by turbolent — APPROVED** [review]
Nice!
