### PR TITLE
Fix crash when invoking a function on an undeclared variable

### LINKED ISSUE #229: Checker crashes when invoking a function of an undeclared variable
### Problem

The following program crashes the checker:

```swift
let x = y.isInstance(Type<Int>())
```

with

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x14d97ea]

goroutine 15 [running]:
testing.tRunner.func1.1(0x1742f40, 0x1fee2e0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0000cc7e0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:943 +0x3f9
panic(0x1742f40, 0x1fee2e0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
github.com/onflow/cadence/runtime/sema.(*Checker).recordResourceInvalidation(0xc000aa8100, 0x1997ea0, 0xc00028f710, 0x0, 0x0, 0x2, 0x0)
	/Users/bastian/Documents/work/cadence/runtime/sema/checker.go:1411 +0x3a
github.com/onflow/cadence/runtime/sema.(*Checker).checkInvocationExpression(0xc000aa8100, 0xc000278960, 0x0, 0x0)
	/Users/bastian/Documents/work/cadence/runtime/sema/check_invocation_expression.go:158 +0x5e0
github.com/onflow/cadence/runtime/sema.(*Checker).VisitInvocationExpression(0xc000aa8100, 0xc000278960, 0xc000aa8100, 0x2795e10)
	/Users/bastian/Documents/work/cadence/runtime/sema/check_invocation_expression.go:27 +0x3f
github.com/onflow/cadence/runtime/ast.(*InvocationExpression).AcceptExp(...)
	/Users/bastian/Documents/work/cadence/runtime/ast/expression.go:339
github.com/onflow/cadence/runtime/ast.(*InvocationExpression).Accept(0xc000278960, 0x19b8640, 0xc000aa8100, 0xb, 0x2)
	/Users/bastian/Documents/work/cadence/runtime/ast/expression.go:335 +0x62
github.com/onflow/cadence/runtime/sema.(*Checker).visitVariableDeclaration(0xc000aa8100, 0xc0000d58c0, 0x0)
	/Users/bastian/Documents/work/cadence/runtime/sema/check_variable_declaration.go:43 +0xc2
github.com/onflow/cadence/runtime/sema.(*Checker).VisitVariableDeclaration(0xc000aa8100, 0xc0000d58c0, 0x10, 0xc0000bc3e8)
	/Users/bastian/Documents/work/cadence/runtime/sema/check_variable_declaration.go:27 +0x3a
github.com/onflow/cadence/runtime/ast.(*VariableDeclaration).Accept(0xc0000d58c0, 0x19b8640, 0xc000aa8100, 0x1, 0x0)
	/Users/bastian/Documents/work/cadence/runtime/ast/variable_declaration.go:51 +0x3e
github.com/onflow/cadence/runtime/sema.(*Checker).VisitProgram(0xc000aa8100, 0xc0000bc370, 0x0, 0x0)
	/Users/bastian/Documents/work/cadence/runtime/sema/checker.go:453 +0x417
github.com/onflow/cadence/runtime/ast.(*Program).Accept(...)
	/Users/bastian/Documents/work/cadence/runtime/ast/program.go:53
github.com/onflow/cadence/runtime/sema.(*Checker).Check.func1(...)
	/Users/bastian/Documents/work/cadence/runtime/sema/checker.go:326
github.com/onflow/cadence/runtime/sema.(*Checker).Check(0xc000aa8100, 0x1977580, 0x1960f70)
	/Users/bastian/Documents/work/cadence/runtime/sema/checker.go:331 +0x154
github.com/onflow/cadence/runtime/tests/checker.ParseAndCheckWithOptions(0xc0000cc7e0, 0x1852f87, 0x35, 0x0, 0x1977580, 0x1960f70, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/bastian/Documents/work/cadence/runtime/tests/checker/utils.go:95 +0x232
github.com/onflow/cadence/runtime/tests/checker.ParseAndCheck(...)
	/Users/bastian/Documents/work/cadence/runtime/tests/checker/utils.go:36
github.com/onflow/cadence/runtime/tests/checker.TestCheckResourceMoveMemberInvocation.func6(0xc0000cc7e0)
	/Users/bastian/Documents/work/cadence/runtime/tests/checker/resources_test.go:4510 +0x89
testing.tRunner(0xc0000cc7e0, 0x18998c8)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1042 +0x357
```

### Notes

Discovered using the fuzzer.

The problem occurs when invoking a member of an undeclared variable

### PR DESCRIPTION
**Pull request by turbolent**
Closes #229 

The first commit fixes the problem. The second commit refactors the code into a function. Probably best viewed in split mode

### CODE REVIEW

File: runtime/sema/check_invocation_expression.go [hunk 1]
```diff
@@ -147,47 +163,42 @@ func (checker *Checker) checkInvocationExpression(invocationExpression *ast.Invo
...
-	return returnType
+	checker.resources.RemoveTemporaryInvalidation(
+		invalidation.resource,
+		invalidation.invalidation,
+	)
+
+	checker.checkResourceUseAfterInvalidation(
+		invalidation.resource,
+		invocationIdentifierExpression,
+	)
```
Comment (psiemens) [inline runtime/sema/check_invocation_expression.go:201]: Nice refactor 👍
