### PR TITLE
Avoid unnecessary static to sema type conversions for `Type` 

### LINKED ISSUE #2748: `Value.Clone` unnecessarily calls `EnsureLoaded`
### Current Behavior

During atree register migration I noticed that cloning a cadence value sometimes requires Programs to be loaded. See stact trace of one such ocurence:

```go
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/interpreter.go:2246 +0x8a
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).EnsureLoaded(0xd762439d40?, {0x1982d60?, 0x109392acf18?})
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/interpreter.go:2222 +0x4f
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).getElaboration(0xe36a6e1170?, {0x1982d60, 0x109392acf18})
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/interpreter.go:4686 +0x25
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).getUserCompositeType(0x1989c78?, {0x1982d60?, 0x109392acf18?}, {0x109376291c0, 0x32})
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/interpreter.go:4751 +0x2d
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).GetCompositeType(0x10786ddb560, {0x1982d60, 0x109392acf18}, {0x1092e276a20?, 0x22629856d2?}, {0x109376291c0, 0x32})
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/interpreter.go:4730 +0x46
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).ConvertStaticToSemaType.func2({0x1982d60?, 0x109392acf18?}, {0x1092e276a20?, 0xed310e1bde0c71bb?}, {0x109376291c0?, 0x40fd5f?})
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/interpreter.go:4664 +0x46
github.com/onflow/cadence/runtime/interpreter.ConvertStaticToSemaType({0x1970fc0?, 0x1077efef4d0?}, {0x1985668?, 0x109392ba090?}, 0x109392abdb0?, 0xd762439d40?)
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/statictype.go:731 +0x579
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).ConvertStaticToSemaType(0xb127be?, {0x1985668?, 0x109392ba090?})
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/interpreter.go:4657 +0x73
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).MustConvertStaticToSemaType(...)
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/interpreter.go:4674
github.com/onflow/cadence/runtime/interpreter.TypeValue.HashInput({{0x1985668?, 0x109392ba090?}}, 0xe36a6e1218?, {{0x40db7d?, 0x15f4de0?}, {0x166bf20?, 0xed310e1bde0c7100?}}, {0x10827f43b28, 0x20, 0x20})
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/value.go:509 +0x36
github.com/onflow/cadence/runtime/interpreter.newHashInputProvider.func1({0x1975c60?, 0x1093762b1e0?}, {0x10827f43b28, 0x20, 0x20})
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/hashablevalue.go:34 +0xe4
github.com/onflow/atree.(*basicDigesterBuilder).Digest(0x109392afd90, 0x109392ba210, {0x1975c60, 0x1093762b1e0})
    
/go/pkg/mod/github.com/onflow/atree@v0.6.0/hash.go:107 +0x94
github.com/onflow/atree.NewMapFromBatchData({0x19840c0?, 0x1078f1ef740}, {0xd2, 0x56, 0x98, 0x62, 0x60, 0xe2, 0xd4, 0xbe}, ...)
    
/go/pkg/mod/github.com/onflow/atree@v0.6.0/map.go:4341 +0x35e
github.com/onflow/cadence/runtime/interpreter.(*DictionaryValue).Clone(0x109392abc70, 0x10786ddb560)
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/value.go:17816 +0x29e
github.com/onflow/cadence/runtime/interpreter.(*CompositeValue).Clone.func1()
    
/go/pkg/mod/github.com/onflow/cadence@v0.39.15-0.20230823153602-c1edd8a467e2/runtime/interpreter/value.go:16345 +0x6b
github.com/onflow/atree.NewMapFromBatchData({0x19840c0?, 0x1078f1ef740}, {0xd2, 0x56, 0x98, 0x62, 0x60, 0xe2, 0xd4, 0xbe}, ...)
    
/go/pkg/mod/github.com/onflow/atree@v0.6.0/map.go:4332 +0x308
github.com/onflow/cadence/runtime/interpreter.(*CompositeValue).Clone(0x10937622dc0, 0x10786ddb560)
```

### Expected Behavior

That shouldn't be necessary, the type ID should already be in the interpreter static type.

more info: https://discord.com/channels/613813861610684416/1108968095982293002/1144314735957909635

### Steps To Reproduce

I reproduced this during a migration. I don't have any small reproduction cases.

### Environment

```markdown
- Cadence version: v0.39.15
```

### PR DESCRIPTION
**Pull request by turbolent**
Closes #2748 

## Description

`interpreter.StaticType` currently does not expose a mechanism to get the type's ID.

`interpreter.TypeValue` needs to get a type ID in two places:
- For the `identifier` field
- For the `HashInput` function, e.g. used when the type value is used as a dictionary key

`interpreter.TypeValue` calculated the type ID by converting the static type to a sema type. This causes the whole program to be loaded, which is inefficient or even unavailable (e.g. during a state migration).

Introduce `func StaticType.ID() TypeID` to allow getting the type ID for a static type without overhead, and remove the unnecessary conversions from static to sema type.

cc @janezpodhostnik 

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: runtime/interpreter/primitivestatictype.go [hunk 1]
```diff
@@ -35,32 +35,12 @@ var PrimitiveStaticTypes = _PrimitiveStaticType_map
 
 type PrimitiveStaticType uint
 
-func (t PrimitiveStaticType) Equal(other StaticType) bool {
```
Comment (turbolent) [inline runtime/interpreter/primitivestatictype.go:38]: Moved down as-is

File: runtime/interpreter/primitivestatictype.go [hunk 2]
```diff
@@ -35,32 +35,12 @@ var PrimitiveStaticTypes = _PrimitiveStaticType_map
...
-
-	return t == otherPrimitiveType
-}
+var _ StaticType = PrimitiveStaticType(0)
 
 const primitiveStaticTypePrefix = "PrimitiveStaticType"
 
 var primitiveStaticTypeConstantLength = len(primitiveStaticTypePrefix) + 2 // + 2 for parentheses
 
-func (t PrimitiveStaticType) MeteredString(memoryGauge common.MemoryGauge) string {
```
Comment (turbolent) [inline runtime/interpreter/primitivestatictype.go:51]: Moved down as-is

File: runtime/interpreter/statictype.go [hunk 3]
```diff
@@ -477,6 +511,25 @@ outer:
...
+				restrictionStrings = append(restrictionStrings, string(restriction.ID()))
+			}
+		}
+		var typeString string
+		if t.Type != nil {
+			typeString = string(t.Type.ID())
+		}
+		t.typeID = TypeID(sema.FormatRestrictedTypeID(typeString, restrictionStrings))
+	}
+	return t.typeID
```
Comment (SupunS) [inline runtime/interpreter/statictype.go:530]: The type ID for restricted types depends on the order of the restrictions. I guess that is OK, because this simply replaces sema.Type.ID(), and that too relies on the order?

**Comment by turbolent** [comment]
@SupunS Could you please have a look? It would unblock me to make the appropriate changes in #2648

**Review by SupunS — APPROVED** [review]

File: runtime/interpreter/statictype.go (hunk 3 above)
Comment (turbolent) [reply runtime/interpreter/statictype.go:530]: Right, this is a current issue for restricted types, see https://github.com/onflow/cadence/issues/2681.
The code here keeps the current order dependency as it is currently, i.e. sema's type ID encoding for restricted types is also based on declaration order / performs no sorting.
